"""Add created_at to saga_steps

Revision ID: 05c86bbacedd
Revises: a4119893fe16
Create Date: 2026-08-07 22:00:18.323239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05c86bbacedd'
down_revision: Union[str, Sequence[str], None] = 'a4119893fe16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saga_steps', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saga_steps', 'created_at')
    # ### end Alembic commands ###
