"""add_address_details_to_orders

Revision ID: 08d17d14c652
Revises: be1cec57a0a7
Create Date: 2026-08-12 00:26:25.168510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d17d14c652'
down_revision: Union[str, Sequence[str], None] = 'be1cec57a0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('pincode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pincode')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
